### PR TITLE
Allow owners to upload photos of dishes - local storage with Paperclip

### PR DESCRIPTION
**Pull request by AmberWilkie**
PT Story: https://www.pivotaltracker.com/story/show/131936243

Changes proposed in this pull request:
- Install Paperclip gem
- Allow for image uploading on create and edit restaurant pages
- Storage images locally in `public` folder

What I have learned working on this feature:
- Working with Paperclip gem (clever!)
- An image storage basically anywhere in the file system can be found by Rails (seems like it, anyway)

Screenshots:
screen shot 2016-10-09 at 1 49 57 pm
screen shot 2016-10-09 at 1 50 39 pm

Ready for review!

### CODE REVIEW

**Comment by AmberWilkie** [comment]
Ok so I accidentally deleted all the files in my public folder. I tried to add them back but having trouble... help?

**Comment by AmberWilkie** [comment]
No, that would be stupid.

**Comment by AmberWilkie** [comment]
Yes, that's exactly what I did. Help me get it back?

**Comment by tochman** [comment]
Not at computer right now. 😜 
@diraulo are you around?

**Comment by AmberWilkie** [comment]
It can wait. It's done as far as I can take it without help.

**Comment by AmberWilkie** [comment]
Got those files back in (and not affecting version control, it would seem).

There's a bunch of fancy testing stuff this thing is capable of, but it's all a bit over my head. I am testing it, but in a hacky way - I go around all the front-end elements and just do `dish.image = 'image'`. I don't know how to test the file selection button (after some significant research).

I'm happy to hear things you want to see before it's accepted, but to get this in a much better situation, I probably need help from someone.

**Pull request merged**
